### ISSUE TITLE
Retrieve Data While SmugMug is in Read-Only Mode

### ISSUE THREAD

**Issue by davenelson** [lildude/phpSmug#18]
According to this post http://www.dgrin.com/showthread.php?t=83918 when SmugMug is in read-only mode it is still possible to retrieve data from the API if done anonymously.

But it appears that phpSmug does not support this as I am currently receiving this error and unable to retrieve data.

**Comment by lildude** [comment]
I'm not sure if this is still an issue with the new API.  I've not managed to encounter a problem with the new API being in read-only mode whilst working on phpSmug 4.0.0 (just released).

If you're able to repro this with phpSmug 4.0.0 (which uses API v2) please let me know and I'll see what I can do.

**Comment by lildude** [comment]
I've not seen any mention of APIv2 having a read-only mode so I doubt this is an issue anymore.

Closing, but please feel free to reopen if you stumble upon this with the new API.
