### ISSUE TITLE
Upload results in duplicate filename

### ISSUE THREAD

**Issue by WaltzKing** [lildude/phpSmug#19]
With phpSmug version 3.5, image uploads result in the FileName being duplicated.  For example, if I upload "foo.jpg", the FileName as stored on the SmugMug site ends up being "foo.jpg, foo.jpg".

I believe this is because the X-Smug-Filename header is being duplicated.  In particular, this bit of code:

       /* Optional Headers */
        foreach( $args as $arg => $value ) {
            if ( $arg == 'File' ) continue;
            $upload_req->setHeader( 'X-Smug-' . $arg, $value );
        }

will cause X-Smug-FileName to be set a second time.

I changed the code like this:

       /* Optional Headers */
        foreach( $args as $arg => $value ) {
            if ( $arg == 'File' ) continue;
            if ( $arg == 'FileName' ) continue;
            $upload_req->setHeader( 'X-Smug-' . $arg, $value );
        }

and the duplicate names went away.  This of course is not the most elegant way to handle the problem but it does illustrate that the duplicate headers is probably the problem.

**Comment by lildude** [comment]
This should now be resolved with phpSmug 4.0.0 I've just released.

Please try updating (phpSmug 4.0.0 is _not_ a drop in replacement for 3.5 due to vast changes in the API and phpSmug) and feel free to reopen if the problem persists.
