### ISSUE TITLE
Implement support for API 2.0

### ISSUE THREAD

**Issue by lildude** [lildude/phpSmug#20]
API 2.0 is currently open to beta testers so lets get phpSmug using it.

**Comment by WaltzKing** [comment]
I for one would be interested in an API 2.0 wrapper.  In particular, I need a way to create 3 levels of folders programmatically.  I've been doing it by hand and it's getting very old very quickly.

**Comment by kujain** [comment]
HI there!
Since Smugmug is shutting down access to API 1.x in a few weeks, I was wondering if there's any development with phpsmug to make it compatible with the new version.

Thank you

**Comment by lildude** [comment]
Oh :poop: I'd completely forgotten about this deadline.  I can't promise anything, but I aim to have something usable by the deadline.

One word of warning: it will _not_ be compatible with earlier versions of phpSmug due to the vast changes in the API itself.

**Comment by WaltzKing** [comment]
Thanks!

**Comment by kujain** [comment]
Thanks Colin!

**Comment by lildude** [comment]
Just a quick update to say I'm progressing nicely on this with most of the functionality now in place.  Just a bit of :lipstick: and a rewrite of the docs to do and we should be all set.

I'm aiming for a deadline of 31 Dec, but should hopefully be done before then.

**Comment by lildude** [comment]
phpSmug 4.0.0 has just been released and it has full support for the v2 API.

Closing this.
