### ISSUE TITLE
redirect to password protected album

### ISSUE THREAD

**Issue by ramsb** [lildude/phpSmug#27]
I am looking for a bit of help and not on twitter.  If this is in the wrong place, please let me know where best to direct my question.

We would like our clients to move from our client area (behind user name and password on our domain) into a password protected smugmug gallery located on a subdomain.  phpSmug is helping with the api tremendously, but I cannot seem to get albums_browse to work (curl error 56).  I am at a loss on how to figure out what is happening.  

Question - how can I make the redirect into a password protected gallery occur using album browse (or if redirect is not possible, what more may be needed for the browse to work)?  

Thank you.

PS - I should have mentioned that I am currently trying this in an anon session and can get the album info via albums_getInfo.

**Comment by lildude** [comment]
Hi @ramsb 

Sorry about the delay in getting back to you.  This is the perfect place for longer more extensive questions and responses.

I've never used album_browse before so I'm not too sure about the behaviour you are seeing.  

Are you still seeing this problem?

If so, let me know and I'll dig in and see if I can work out what's going on.

— Colin

**Comment by ramsb** [comment]
Hello Colin,
Thanks for the reply and your work on the wrapper.  It has really helped me
come up to speed on working through the api.  At present I have a soln in
place that seems to be okay for our current needs.  Thanks again.

**Comment by lildude** [comment]
Great! Good to hear it.
