### ISSUE TITLE
POST an Album

### ISSUE THREAD

**Issue by Xiora** [lildude/phpSmug#37]
Hello, I'm trying to create an album for later upload images. My idea is that every user of my web has an own album, so they have to be created automatically.

The problem I have encountered is that when I put the POST method, it returns me this error: 400 Bad Request response: {"Options":{"Methods":["POST"],"ParameterDescription":{"Boolean":"For true return type true or 1, for false type false o (truncated...) (Error Code: 400)

In Live API from SmugMug, the same JSON and URL works correctly.

Here is my code:

$name = "Big Cats";
$urlName = "BigCats";
    
$option = array(
        "AutoRename"=> false,
        "CoverImageUri"=> null,
        "Description"=> "",
        "HideOwner"=> false,
        "HighlightImageUri"=> null,
        "Name"=> $name,
        "Keywords"=> [],
        "Password"=> "",
        "PasswordHint"=> "",
        "Privacy"=> 1,
        "SecurityType"=> 1,
        "ShowCoverImage"=> false,
        "SmugSearchable"=> 1,
        "SortDirection"=> 2,
        "SortMethod"=> 5,
        "Type"=> 4,
        "UrlName"=> $urlName,
        "WorldSearchable"=> 1
);

$option = json_encode($option);
$client->post('node/xxxxx!children', $option); //xxxxx => nodeId

**Comment by lildude** [comment]
I suspect this is your problem:

```
$option = json_encode($option);
```

You don't need to `json_encode()` the array yourself as phpSmug takes advantage of Guzzle's functionality to do that for you as part of creating the POST request. 

Try removing that line entirely.

**Comment by Xiora** [comment]
OMG, thank you! I had tried without the json_encode and it did not work, then I made some adjustments with the json_encode, and I had not thought to remove it.
