### ISSUE TITLE
Get client error code

### ISSUE THREAD

**Issue by Xiora** [lildude/phpSmug#38]
Hello, in my attempt to create albums automatically, I have realized, that if the UrlName already exists, it directly does not return anything to me, but I skip the 409 client error, but without being object or anything.

How can I get this code to control it with an if?

My idea is that if it already exists, add a number to the UrlName using a function, and if that also exists, add 1 to the previous number. This part has already been solved, I lack control if it exists...

Thanks in advance!

**Comment by lildude** [comment]
The best thing to do is catch the `GuzzleHttp\Exception\ClientException` exception Guzzle throws when you attempt to create an album that already exists with that name, adjust the name by appending 1 to the number and try again.

For example:

```php
try {
  $response = $client->post('folder/user/example/Cats!albums', $options);
} catch (GuzzleHttp\Exception\ClientException $e) {
  if ($e->getCode() == 409) {
     // retry code here
  };
}
```

You may want to put this in a for or while loop to keep incrementing until you finally get a unique name.

**Comment by lildude** [comment]
I'm gonna take the silence on this issue as confirmation that you're resolved all your issues and I've answered all your questions. If you have any further issues or questions, please feel free to open a new issue.
