### ISSUE TITLE
$callback url doesn't work!

### ISSUE THREAD

**Issue by tylertesting1** [lildude/phpSmug#45]
Hi there, 
I have a problem with using this lib.
```php
    require_once 'vendor/autoload.php';
    $options = [
        'AppName' => SMUGMUG_APPNAME . '/1.0 (' . HTTPS_ROOT . ')',
        '_verbosity' => 1, 
        'OAuthSecret' => SMUGMUG_OAUTH_SECRET, 
    ];
$client = new phpSmug\Client(SMUGMUG_APIKEY, $options);
$callback = 'https://aaa.com/smugmugs/callback';
$request_token = $client->getRequestToken($callback);
$html                        = "<p>Click <a href='" . $client->getAuthorizeURL() . "' target='_blank'><strong>HERE</strong></a> to Authorize.</p>";
echo $html;

```
when I click to get access from smugmug and it just redirect to the root path of my site:
`https://aaa.com/?oauth_token=XXX&...`
Why can't it redirect to the callback url i specified above?
Anything I did wrong on my code above?

Thanks.

**Comment by tylertesting1** [comment]
Hi @lildude , thank you for your reply.

Unfortunately, i am sure the browser or server is not redirecting and the initial request is going to the wrong url.
Please take a look at my screenshots below:
![image](https://user-images.githubusercontent.com/34469186/41581519-47bb1072-73d1-11e8-96ca-2daf6fa57957.png)

![image](https://user-images.githubusercontent.com/34469186/41581480-2bd16dfc-73d1-11e8-881c-836873b3487a.png)

**Comment by lildude** [comment]
Hmmmm. This is definitely working for me.  Have you tried testing with the [example-oauth.php](https://github.com/lildude/phpSmug/blob/master/examples/example-oauth.php) file?

As an initial test, replace just these with your values: https://github.com/lildude/phpSmug/blob/097d6dfe5d73ed9d2b4f11d5c813229f76d46a6d/examples/example-oauth.php#L25-L27

If that works, then try replacing the callback url at https://github.com/lildude/phpSmug/blob/097d6dfe5d73ed9d2b4f11d5c813229f76d46a6d/examples/example-oauth.php#L59 with the callback URL you're trying to use.

**Comment by lildude** [comment]
I replaced the callback in the example-oauth.php with the one you used in your OP (I know it's invalid) and it definitely redirects there:

![image 2018-06-19 16-41-55](https://user-images.githubusercontent.com/627280/41608183-ccc669ca-73df-11e8-9011-8e4cc24fc1d7.png)
