### ISSUE TITLE
Feature request: support for _config

### ISSUE THREAD

**Issue by asherber** [lildude/phpSmug#49]
The SmugMug API supports an advanced syntax for expansions using a `_config` parameter, documented at https://api.smugmug.com/api/v2/doc/advanced/config.html

Currently, I can make use of this in phpSmug by creating the appropriate array and then encoding it myself:

```php
$advanced = [
    'filter' => [ 'Name', 'Description' ],
    'filteruri' => [ 'HighlightImage' ],
    'expand' => [
        'HighlightImage' => [
            'filter' => [ 'ThumbnailUrl' ],
            'filteruri' => []
        ]
    ]
];

$request_options = [
    '_expandmethod' => 'inline',
    '_config' => json_encode($advanced)
];

$client->get('user/me!albums', $request_options);
```

It would be nice if phpSmug recognized the `_config` key in an `$options` array and performed the JSON encoding automatically.

**Comment by lildude** [comment]
Seems reasonable enough. Will take a look when I do the other expansions stuff.
