### ISSUE TITLE
400 Error code creating album, please help.

### ISSUE THREAD

**Issue by davidvexel** [lildude/phpSmug#57]
Has anyone had 400 Bad Request errors when creating albums?

This is my code
```php
try {
    // Create
    $album = $client->post( $endpoint, $options );
    return $album;
 } catch ( BadResponseException $ex ) {
    var_dump( $ex->getResponse()->getBody()->getContents() ); 
}
```
This is my request data:

```php
  'UrlName' => string 'wp-smugmu-local-test-32' (length=23)
  'Name' => string 'Test' (length=4)
  'Privacy' => string 'Public' (length=6)
  'Description' => string 'Album published from a WP Gallery in smugmug website.' (length=54)
```

This is my endpoint `/api/v2/folder/user/myuser/January-2019!albums`

And I'm getting this error:

```{"Response":{"Uri":"/api/v2/folder/user/myuser/January-2019!albums?_verbosity=1","Locator":"Album","LocatorType":"Objects"},"Code":400,"Message":"Bad Request"}```

Any ideas? 

Thanks in advance!

**Comment by davidvexel** [comment]
If I change the ÙrlName` to `WP-chico-local-test-smugmug-324` works. lol.

**Comment by davidvexel** [comment]
Seems like the `wp` lowercase letters doesn't like to `UrlName` param, it only works if I use them as uppercase `WP`... Very odd. Closing this issue for now. Thanks.

**Comment by danielmreck** [comment]
@davidvexel, I believe that SmugMug folders, galleries, and pages are required to start with a number or a capital letter.

The on the live site, SmugMug site will rewrite HTTP requests for folders, galleries, and pages that start with a lowercase letter to make them start with uppercase.  However, the rest of the URL will still pay attention to case.

As such, _example.com/January-2019/wP-chico-local-test-smugmug-324_ will resolve to _example.com/January-2019/WP-chico-local-test-smugmug-324_ and display your gallery.  But _example.com/January-2019/wp-chico-local-test-smugmug-324_ will throw a 404 error.

I do not believe the API will correct for lowercase initial letters on requests.

**Comment by davidvexel** [comment]
Hey @danielmreck, you're so right, I didn't know about this and made me struggle for a bit, thanks you!
