### ISSUE TITLE
404 returned just for our Smugmug site album list

### ISSUE THREAD

**Issue by ajl199** [lildude/phpSmug#59]
I don't know whether this is something anyone has seen before or can provide any advice about, but I am at my wits' end because it seems to make no sense at all.

Our app, which was working fine for most of the year up to last week, now refuses to play due to a 404 error when trying to access /user/ouraccount!albums

Bizarrely:
    - if I change ouraccount in the above to a different Smugmug account, it works;
    - if I change !albums to another endpoint like !featuredalbums, I get no 404; and
    - if I copy the 404'd URL from the app's logs/terminal and paste it into a browser, it sometimes works

I've stripped it down to the code to its bare minimum and here's the offending bit:

    $client=smugmug_instantiate();
    $repositories = $client->get('user/********!albums');
    foreach ($repositories->Album as $alb)
        {
        print "Album: ".$alb->Name."\n";
        }

Literally, if I change our account handle in the above to the name of another account, I get a list of their albums. If I put it back to ours, I get a 404. I even tried changing the name of our Smugmug account temporarily, but got the same behaviour as above with the new name.

The whole of the script I'm testing with is only 16 lines long including the above bit and the instantiate function. If I move it to a different computer on a different network with a fresh phpSmug installation, I _still_ get the same behaviour.

The actual error when run in the terminal looks like this:

```
$ php tryme.php 
PHP Fatal error:  Uncaught GuzzleHttp\Exception\ClientException: Client error: `GET https://api.smugmug.com/api/v2/user/*******!albums` resulted in a `404 Not Found` response:
{"Response":{"Uri":"/api/v2/user/********!albums","Locator":"Album","LocatorType":"Objects","UriDescription":"All of use (truncated...)
 in /tmp/smuglocal/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113
Stack trace:
#0 /tmp/smuglocal/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /tmp/smuglocal/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /tmp/smuglocal/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /tmp/smuglocal/vendor/guzzlehttp/promises/src/TaskQueue.php(47): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
#4 /tmp/smuglocal/vendor/guzzl in /tmp/smuglocal/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php on line 113
```

Is this at all familiar?

Many thanks,

Adrian

**Comment by lildude** [comment]
🤔 this sounds like possible something outside of phpSmug, especially as you say:

> - if I copy the 404'd URL from the app's logs/terminal and paste it into a browser, it sometimes works

That would indicate whatever is producing the 404 has nothing to do with phpSmug.

If you're able to reliably reproduce the 404 using something like curl, I'd suggest contacting the SmugMug support peeps with a shell script they can use to reliably reproduce the issue themselves.
